name = "mon-worker"                    # Remplace par le nom de ton Worker
compatibility_date = "2025-08-18"     # Date de compatibilité, à jour
main = "index.js"                 # Fichier JS généré par la transpilation PHP
workers_dev = true                     # Déploiement sur workers.dev
